### ISSUE TITLE
CI build failing on `brew test-bot --only-formulae`

### ISSUE THREAD

**Issue by miguelaferreira** [Homebrew/homebrew-test-bot#661]
I'm seeing an error I cannot understand when running `brew test-bot --only-formulae` for my taps repository.

This is the error message:
```
==> brew linkage --test miguelaferreira/tools/devex-cli
==> FAILED
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
```

Here's the [workflow full log](https://github.com/miguelaferreira/homebrew-tools/runs/3574392516#step:8:29).

I could use any help figuring out what this error means and how can I fix it.

**Comment by carlocab** [comment]
Your build has dependence on `zlib`, which isn't portable. Add `uses_from_macos "zlib"` to your formula's dependencies.

**Comment by miguelaferreira** [comment]
Hi @carlocab thanks for your help.
I've added `uses_from_macos "zlib"` to the formulas (see https://github.com/miguelaferreira/homebrew-tools/pull/5/files#diff-a4e8c4ef2098009481eef7964aac8e2f0d52537a718f9649deef67409f3f28adR10), but the build still breaks with the same error.

It's the ubuntu build that still fails with this error.
```
==> FAILED
Unwanted system libraries:
  /lib/x86_64-linux-gnu/libz.so.1
```
[Full log](https://github.com/miguelaferreira/homebrew-tools/pull/5/checks#step:8:50).

**Comment by carlocab** [comment]
Ah, your formula installs pre-built binaries, which is why adding the `zlib` dependency doesn't help. You have a few alternatives:

1. Ignore the error and drop the `uses_from_macos "zlib"` line. Your formula won't work on systems that don't provide `zlib`.
2. Build your binaries from source in the formula.
3. Keep the `uses_from_macos "zlib"` and modify the `RPATH`s in your binaries to be able to find Homebrew `zlib`. You can use `patchelf` for this.

Not 100% certain 3 works, but I don't see why it shouldn't.

**Comment by miguelaferreira** [comment]
Thanks again @carlocab, I think I'm only going to ignore the error and remove that step from my CI workflow. 

These binaries are java applications created with graalvm native image, so building them from source on install is just too heavy. I can't make them casks either because that's macOS specific, so a formula is the way I think is best to offer them. Maybe a bottle would be the best way? Unfortunately I don't find enough documentation to teach me how to make those.

In addition my formula doesn't really depend on "zlib", the only reason I see for this implicit dependency to be created is the fact that the package being downloaded is a `tar.gz` archive, and both OSs I'm targeting include `tar` with `gzip` support. 
Saying my formula has a dependency on "zlib" sounds to me like saying my formula has a dependency on `lib-curl` because an archive needs to be downloaded, or a dependency on `ls` because files need to be listed at some point. 
I can imagine there's a good explanation for this dependency, but I don't find enough documentation to learn these things either.

**Comment by carlocab** [comment]
> Saying my formula has a dependency on "zlib" sounds to me like saying my formula has a dependency on `lib-curl` because an archive needs to be downloaded, or a dependency on `ls` because files need to be listed at some point.

I'm afraid you're mistaken.

When I say that your formula has dependence on `zlib`, I mean that your binary will not work on systems that do not have `zlib` installed at `/lib/x86_64-linux-gnu` even if it is successfully downloaded, unzipped, and installed.

You can see this using `objdump` or `ldd`:
```
❯ objdump -p devex-Linux-v1.0.0

devex-Linux-v1.0.0:     file format elf64-x86-64
[snip]
Dynamic Section:
  NEEDED       libz.so.1
  NEEDED       libpthread.so.0
  NEEDED       libdl.so.2
  NEEDED       libc.so.6
```
```
root@95d0d9214baa:/tmp# ldd devex-Linux-v1.0.0
        linux-vdso.so.1 =>  (0x00007ffe1edf1000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fef84ed7000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fef84cba000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fef84ab6000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fef846ec000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fef89bf6000)
```

Here's what happens when I try to run your binary on a system that does not have `/lib/x86_64-linux-gnu/libz.so.1`
```
root@95d0d9214baa:/tmp# ./devex-Linux-v1.0.0 -h
./devex-Linux-v1.0.0: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```
