### ISSUE TITLE
Don't skip if "has dependencies without compatible bottles" only affects `:build` dependencies

### ISSUE THREAD

**Issue by mgeier** [Homebrew/homebrew-test-bot#857]
I'm getting this warning (see https://github.com/SoundScapeRenderer/homebrew-ssr/actions/runs/3694432890/jobs/6255609082), and no bottle is created:

```
Warning: soundscaperenderer/ssr/libmysofa has dependencies without compatible bottles:
==> SKIPPED soundscaperenderer/ssr/libmysofa
  cmake
```

I'm wondering if this really has to be skipped, since the dependency `cmake` is only a build dependency, and if I understand the situation correctly, it is not needed when bottles are used, right?

Could this check be modified to exclude build dependencies?

I guess this is the relevant code:

https://github.com/Homebrew/homebrew-test-bot/blob/6cf3c3cc5266cfd196c9d908a7f0aa762d0042a9/lib/tests/formulae.rb#L301-L314

**Comment by MikeMcQuaid** [comment]
> Could this check be modified to exclude build dependencies?

If it's a direct dependency: no, because this logic always builds a bottle or builds from source.

I don't think this behaviour is the case for indirect dependencies.

Happy to keep chatting here but closing as this is something that will need to turn into a PR from you (once we've decided if/what that should be) rather than something we're planning on working on.

**Comment by carlocab** [comment]
Even if this check were skipped, `test-bot` will fail at a later stage because it will try to install `cmake` from Homebrew/core but find that it does not have a bottle.

That said: skipping a bottle build when dependencies are not bottled, even if the dependency with a missing bottle is only a build dependency, is exactly the behaviour we want for Homebrew/core. As a consequence, I don't think we want to change the default behaviour here.

We could skip the check when requested with an option, but that still leaves it to you to resolve the problem of avoiding a failure when `test-bot` tries to install `cmake` (unless it is pre-installed on GitHub runners?). But that option will still become almost useless when GitHub drops Catalina (which should be in the near-ish future), so I'm not certain it's worth it.

**Comment by MikeMcQuaid** [comment]
> We could skip the check when requested with an option

To be honest: I'd rather not add options to test bot that we aren't using ourselves. The chance of breakage is too high.

**Comment by mgeier** [comment]
Thanks for the quick responses!

I'm very new to this topic (I tried making my first formula less than a week ago, and I've never used Ruby before), so I'm sure I don't fully understand how any of this works, and I would be thankful for some clarification.

> Even if this check were skipped, `test-bot` will fail at a later stage because it will try to install `cmake` from Homebrew/core but find that it does not have a bottle.

OK, thanks, I think I understand the problem better now.

But theoretically, the bot could still try to build any `:build` dependencies from source if they don't have a bottle, right?

Or do you generally want to avoid building dependencies from source, because it would use too many resources?

Or are you assuming that if there is no bottle, there is a problem with building the formula (in my case `cmake`) on the current platform, and it doesn't make sense to even try building it from source?

I couldn't find out if there was a build problem, I only found a commit where the `catalina` bottle was removed from the list of bottles: https://github.com/Homebrew/homebrew-core/commit/a9d4e0c1b621ba22c314ab3b71b031c167437980. I didn't find any reasoning for that, but I probably just missed it.

> But that option will still become almost useless when GitHub drops Catalina (which should be in the near-ish future), so I'm not certain it's worth it.

Yes that's true in the specific case I was mentioning.

I was just wondering if there is a more general problem of the build bot over-eagerly skipping bottles ... but maybe I was wrong.

> the problem of avoiding a failure when `test-bot` tries to install `cmake` (unless it is pre-installed on GitHub runners?)

I don't think `cmake` should be a special case, but just for the record: yes, CMake ist installed on the Github runners.

Cmake 3.24.2: https://github.com/actions/runner-images/blob/main/images/macos/macos-10.15-Readme.md
Cmake 3.25.1: https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md
Cmake 3.25.1: https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md

**Comment by MikeMcQuaid** [comment]
> Or do you generally want to avoid building dependencies from source, because it would use too many resources?
> Or are you assuming that if there is no bottle, there is a problem with building the formula (in my case `cmake`) on the current platform, and it doesn't make sense to even try building it from source?

Both/either of these!

> I couldn't find out if there was a build problem, I only found a commit where the `catalina` bottle was removed from the list of bottles: [Homebrew/homebrew-core@a9d4e0c](https://github.com/Homebrew/homebrew-core/commit/a9d4e0c1b621ba22c314ab3b71b031c167437980). I didn't find any reasoning for that, but I probably just missed it.

Catalina is no longer supported so we no longer build bottles for it.



> I don't think `cmake` should be a special case, but just for the record: yes, CMake ist installed on the Github runners.

We can only use dependencies from inside Homebrew on Homebrew, unfortunately.

**Comment by mgeier** [comment]
Thanks a lot for the clarification!

> Catalina is no longer supported so we no longer build bottles for it.

I wasn't aware of that!
I guess I could have saved you and me some time had I known that.
